---
# tasks file for iac-ansible-common-server

- selinux:
    state: disabled
    
- yum: 
    name: "{{item}}"
    state: latest 
  with_items:
    - bash-completion
    - bash-completion-extras
    - bind-utils
    - bzip2
    - cifs-utils
    - curl
    - epel-release
    - finger
    - htop
    - lsof
    - mlocate
    - nfs-utils
    - nmap
    - screen
    - sudo
    - sysstat
    - tcpdump
    - tree
    - tzdata
    - unzip
    - vim
    - zip
    - wget
...
