---
# tasks file for iac-ansible-common-server
- selinux:
    state: disabled
    
- yum: name={{item}} state=latest 
  with_items:
          - bash-completion
          - bind-utils
          - bzip2
          - ccze
          - curl
          - epel-release
          - finger
          - htop
          - lsof
          - mlocate
          - nfs-utils
          - nmap
          - screen
          - sudo
          - sysstat
          - tcpdump
          - tree
          - tzdata
          - unzip
          - vim
          - wget
...
