---
# tasks file for ansible-role-commonserver

- yum: 
    name: "{{ item }}" 
    state: latest
  with_items:
    - tzdata
    - chrony
  when: ( ansible_os_family == "RedHat" and ansible_distribution_major_version == "7" )
  register: PACKAGE
  notify:
    - Start chronyd
    
- apt: 
    name: "{{ item }}" 
    state: latest 
    update_cache: yes
  with_items:
    - tzdata
    - chrony
  when: ( ansible_os_family == "Debian" and ansible_distribution_major_version == "7" )
  register: PACKAGE
  notify:
    - Start chronyd
    
- timezone:
        name: America/Sao_Paulo
        
##
#- name: Remove Zone Info
#  file:
#    path: /etc/localtime
#    state: absent
#
#- name: copying file Time Zone
#  copy:
#    src: Localtime_Sao_Paulo
#    dest: /usr/share/zoneinfo/America/Sao_Paulo
#
#- name: Link Simbolico NTP
#  file:
#    src: /usr/share/zoneinfo/America/Sao_Paulo
#    dest: /etc/localtime
#    state: link
#
#- name: Set time Zone Info and Hour
#  shell: zdump -v /etc/localtime | egrep '201[89]'
##
...
