---
# tasks file for iac-ansible-common-server

- selinux:
    state: disabled
    
- systemd:
    state: stopped
    name: firewalld.service     
    enabled: no
    masked: yes
    force: yes
  ignore_errors: yes
  when: 
    - ansible_distribution == "CentOS" 
    - YUM2PROXY is success
...
