---
# tasks file for iac-ansible-common-server
- name: "Desabilitando SELINUX"
  selinux:
    state: disabled

- name: "Desabilitando Firewalld"
  notify:
    - Disable Firewalld

- name: "Habilitando tuned"
  shell: tuned-adm profile throughput-performance
  notify:
    - Start Tuned
...
