---
##
- name: "Criando grupos administrativos"
  group: 
    name: "{{ item }}"
    state: present
    system: yes
  with_items: 
    - "backup"
    - "dba"
    - "monitoramento"
    - "operacao"
    - "sudo"
    - "suporte"
    - "helpdesk"
    - "wheel"
## -------------------------------------------------------------------------------------------##        
- name: "Adiciona o usuarios da Operacao N3"
  user: 
    state: present
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    createhome: true
    home: "/home/{{ item.name }}"
    shell: /bin/bash
    group: operacao
    groups: operacao,wheel,sudo
    update_password: always
    comment: "{{ item.comm }}"
  with_items:
    - { name: 'araujo', password: '$1$IghpWON4$F20QFZI07pSsGXujh7Ros1', comm: 'araujo@{{ MEUDOMINIO }}' }
    - { name: 'alfredo', password: '$1$P8FOYcQN$6a7L8EHrFgJK5e84z0POk.', comm: 'alfredo@{{ MEUDOMINIO }}' }
    - { name: 'tominaga', password: '$1$Q5JyJUPb$JcR7aHJqLIR7WztMhwH6l/', comm: 'tominaga@{{ MEUDOMINIO }}' }
    - { name: 'manzano', password: '$1$nfVurj1S$huqgz4cfpTdSlerRo7Ofa0', comm: 'manzano@{{ MEUDOMINIO }}' }
    - { name: 'alisson', password: '$1$nfVurj1S$huqgz4cfpTdSlerRo7Ofa0', comm: 'suporte@{{ MEUDOMINIO }}' }
  register: RCUSER

- authorized_key:
    user: araujo
    state: present
    exclusive: True
    key: https://github.com/wluisaraujo.keys
    validate_certs: False
  when: ( RCUSER is success )
## -------------------------------------------------------------------------------------------##
- name: "Adiciona o usuarios do Suporte N2"
  user: 
    state: present
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    createhome: true
    home: "/home/{{ item.name }}"
    shell: /bin/bash
    group: suporte
    groups: suporte, helpdesk
    update_password: always
    comment: "{{ item.comm }}"
  with_items:
    - { name: 'astolfo', password: '$1$iu8fF8nc$tZBNmvxI79ljeRbbUi47d0', comm: 'astolfo@{{ MEUDOMINIO }}' }
## -------------------------------------------------------------------------------------------##                        
- name: "Adiciona o usuarios do Helpdesk"
  user: 
    state: present
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    createhome: true
    home: "/home/{{ item.name }}"
    shell: /bin/bash
    group: helpdesk
    groups: helpdesk
    update_password: always
    comment: "{{ item.comm }}"
  with_items:
    - { name: 'helpdesk', password: '$1$iu8fF8nc$tZBNmvxI79ljeRbbUi47d0', comm: 'suporte@{{ MEUDOMINIO }}' }
## -------------------------------------------------------------------------------------------##  
- name: "Adiciona o usuarios do Monitoramento"
  user: 
    state: present
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    createhome: true
    home: "/home/{{ item.name }}"
    shell: /bin/bash
    group: monitoramento
    groups: monitoramento
    update_password: always
    comment: "{{ item.comm }}"
  with_items:
    - { name: 'monitoramento', password: '$1$IEpqfE.4$ZISVJI9qFWyeo8qKMI5RM.', comm: 'monitoramento@{{ MEUDOMINIO }}' }
  
- authorized_key:
    user: monitoramento
    state: present
    key: "{{ lookup('file', 'monitoramento_ssh_keys') }}"    
## -------------------------------------------------------------------------------------------##        
- name: "Adiciona o usuarios DBA"
  user: 
    state: present
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    createhome: true
    home: "/home/{{ item.name }}"
    shell: /bin/bash
    group: dba
    groups: dba,wheel,sudo
    update_password: always
    comment: "{{ item.comm }}"
  with_items:
    - { name: 'pateta', password: '$1$u9hDDkXi$JgEf2668EraOPEk1Hz7BU1', comm: 'pateta@{{ MEUDOMINIO }}' }
    - { name: 'donald', password: '$1$ZUPXxQ7z$Hu/awnrxWez7OXhRVTAaI/', comm: 'donald@{{ MEUDOMINIO }}' }
## -------------------------------------------------------------------------------------------##            
- name: "Adiciona o usuarios Backup"
  user: 
    state: present
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    createhome: true
    home: "/home/{{ item.name }}"
    shell: /bin/bash
    group: backup
    groups: backup,wheel,sudo
    update_password: always
    comment: "{{ item.comm }}"
  with_items:
    - { name: 'backup', password: '$1$Xh26LNXw$uMNxai0q5XWP2PqtyLNxv1', comm: 'backup@{{ MEUDOMINIO }}' }
    - { name: 'urameshi', password: '$1$iu8fF8nc$tZBNmvxI79ljeRbbUi47d0', comm: 'urameshi@{{ MEUDOMINIO }}' }
...
