---
# tasks file for ansible-role-commonserver
- command: setenforce 0

- replace:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    replace: 'SELINUX=disabled'

- name: "Desabilitando SELINUX"
  selinux:
    state: disabled

- name: "Desabilitando Firewalld"
  notify:
    - Disable Firewalld

- name: "Habilitando tuned"
  shell: tuned-adm profile throughput-performance
  notify:
    - Start Tuned
...
