---
## tasks file for common-server
- yum:
    name: sudo
    state: present
  when: ( ansible_os_family == RedHat )
  register: SUDOINSTALLED

- apt:
    name: sudo
    state: present
    update_cache: true
  when: ( ansible_os_family == Debian )
  register: SUDOINSTALLED

- zypper:
    name: sudo
    state: present
    update_cache: true
  when: ( ansible_os_family == Suse )
  register: SUDOINSTALLED

##
#- name: Habilitando configuracoes do SUDO
#  lineinfile:
#    path: /etc/sudoers
#    state: present
#    #regexp: '{{ item.checkconf }}'     
#    line: "{{ item.insertconf }}"
#    owner: root
#    group: root
#    mode: 0440
#    validate: '/usr/sbin/visudo -cf %s'
#  with_items:
#    - { checkconf: '^Defaults	logfile',       
#        insertconf: 'Defaults	logfile="/var/log/sudo.log"' 
#      }
#    - { checkconf: '^Cmnd_Alias	logfile',       
#        insertconf: 'Cmnd_Alias SUPORTEN1 = /usr/bin/systemctl * snmpd, /bin/systemctl * snmpd, /sbin/service snmpd *, /usr/sbin/service snmpd * '
#      }
#    - { checkconf: '^Cmnd_Alias	logfile',       
#        insertconf: 'Cmnd_Alias SUPORTEN2 = /usr/bin/systemctl * apache2, /bin/systemctl * apache2, /sbin/service apache2 *, /usr/sbin/service apache2 *, /usr/bin/systemctl * httpd, /bin/systemctl * httpd, /sbin/service httpd *, /usr/sbin/service httpd * '
#      }
## END SUDO CONF
  
#- name: Habilitando USERS SUDO
#  lineinfile: 
#    path: /etc/sudoers
#    state: present
#    regexp: '{{ item.checkreg }}'     
#    line: '{{ item.insertline }}'
#    owner: root
#    group: root
#    mode: 0440
#    validate: '/usr/sbin/visudo -cf %s'
#  with_items:
#    - { checkreg: '^%wheel',                    
#        insertline: '%wheel  ALL=(ALL:ALL) ALL'                     }
#    - { checkreg: '^%sudo',                     
#        insertline: '%sudo   ALL=(ALL:ALL) ALL'                     }
#    - { checkreg: '^%backup',            
#        insertline: '%backup  ALL=(ALL:ALL) ALL'           }
#    - { checkreg: '^%dba',               
#        insertline: '%dba  ALL=(ALL:ALL) ALL'              }
#    - { checkreg: '^%operacao',          
#        insertline: '%operacao  ALL=(ALL:ALL) ALL'         }
#    - { checkreg: '^%suporte1',         
#        insertline: '%suporte1 ALL = SUPORTEN1'            }
#    - { checkreg: '^%suporte2',         
#        insertline: '%suporte2 ALL = SUPORTEN1, SUPORTEN2' }

#END PLAYBOOK
...
