---
# tasks file for ansible-role-commonserver

- name: Definido variaveis de ambiente
  lineinfile:
    path: /etc/environment
    state: present
    line: "{{ item }}"
  with_items:
    - export http_proxy="proxy.{{ MEUDOMINIO }}:3128"
    - export https_proxy="proxy.{{ MEUDOMINIO }}:3128"
    - export ftp_proxy="proxy.{{ MEUDOMINIO }}:3128"
    - export ftps_proxy="proxy.{{ MEUDOMINIO }}:3128"
    - export no_proxy="127.0.0.1, localhost"

- lineinfile:
    path: /etc/yum.conf
    state: present
    line: proxy=http://proxy.{{ MEUDOMINIO }}:3128
  register: YUM2PROXY
  when: ( ansible_os_family == "RedHat" )

- lineinfile:
    path: /etc/apt/apt.conf.d/80proxy
    state: present
    line: "{{ item }}"
    create: yes
  with_items:
    - Acquire::http::proxy "http://proxy.{{ MEUDOMINIO }}:3128/";
    - Acquire::https::proxy "https://proxy.{{ MEUDOMINIO }}:3128/";
    - Acquire::ftp::proxy "ftp://proxy.{{ MEUDOMINIO }}:3128/";
  register: APT2PROXY
  when: ( ansible_os_family == "Debian" )

- name: Definido variaveis de perfil
  lineinfile:
    path: /etc/profile
    state: present
    line: "{{ item }}"
  with_items:
    - 'export HISTTIMEFORMAT="[%d/%m/%y %T] "'
    - 'export TMOUT=600'
 
- replace:
    dest: /etc/logrotate.conf
    regexp: '^#compress'
    replace: 'compress'

#- name: Configurando /etc/hosts.allow 
#  lineinfile: 
#    path: /etc/hosts.allow
#    line: "{{ item }}"
#  with_items:
#          - 'ALL: ALL: spawn /bin/echo "Tentativa de acesso em [$(/bin/date)] - Origem [ %u@%h (%n) ]" &>> /var/log/tcpwrappers.log'
#          - 'ALL: ALL: spawn /bin/logger "Tentativa de acesso em [$(/bin/date)] - Origem [ %u@%h (%n) ]"'

#  - replace:
#      dest: /tmp/sshd_config
#      regexp: "^{{ item.origem }}"
#      replace: "{{ item.destino }}"
#    with_items:
#      - { origem: '#Port',                   destino: 'Port 22' }
#      - { origem: '#PermitRootLogin',       destino: 'PermitRootLogin yes' }
#      - { origem: '#GSSAPIAuthentication',   destino: 'GSSAPIAuthentication no' }
#      - { origem: '#TCPKeepAlive',          destino: 'TCPKeepAlive yes' }
#      - { origem: '#UseDNS',                 destino: 'UseDNS no' }
#      - { origem: 'Port',                       destino: 'Port 22' }
#      - { origem: 'PermitRootLogin',            destino: 'PermitRootLogin yes' }
#      - { origem: 'GSSAPIAuthentication',       destino: 'GSSAPIAuthentication no' }
#      - { origem: 'TCPKeepAlive',               destino: 'TCPKeepAlive yes' }
#      - { origem: 'UseDNS',                     destino: 'Port 22' }#

...
