---
# tasks file for iac-ansible-common-server

- name: Definido variaveis de ambiente
  lineinfile:
    path: /etc/environment
    state: present
    line: "{{ item }}"
  with_items:
    - export http_proxy="proxy.dexter.com.br:3128"
    - export https_proxy="proxy.dexter.com.br:3128"
    - export ftp_proxy="proxy.dexter.com.br:3128"
    - export ftps_proxy="proxy.dexter.com.br:3128"
    - export no_proxy="127.0.0.1, localhost"

- lineinfile:
    path: /etc/yum.conf
    state: present
    line: proxy=http://proxy.dexter.com.br:3128
  register: YUM2PROXY
  when: ( ansible_os_family == "RedHat" )

- lineinfile:
    path: /etc/apt/apt.conf.d/80proxy
    state: present
    line: "{{ item }}"
    create: yes
  with_items:
    - Acquire::http::proxy "http://proxy.dexter.com.br:3128/";
    - Acquire::https::proxy "https://proxy.dexter.com.br:3128/";
    - Acquire::ftp::proxy "ftp://proxy.dexter.com.br:3128/";
  register: APT2PROXY
  when: ( ansible_os_family == "Debian" )
...
