---
# tasks file for iac-ansible-common-server

- name: Configurando ambiente Linux
  import_tasks: linux-environment.yml
  when: ( ansible_system == "Linux" )

- name: Aplicando Timezone America/SP
  import_tasks: timezone.yml
  when: ( ansible_system == "Linux" )

- name: Aplicando Parametros Sysctl
  import_tasks: sysctl.yml
  when: ( ansible_system == "Linux" )

- name: Instalando pacotes (OS Base Debian)
  import_tasks: base-debian.yml
  when: ( ansible_os_family == "Debian" and APT2PROXY is success ) 
  
- name: Instalando pacotes e aplicando config (OS Base Redhat)
  import_tasks: base-redhat.yml
  when: ( ansible_distribution == "RedHat" and YUM2PROXY is success )

- name: Instalando pacotes e aplicando config (OS Base CentOS)
  import_tasks: base-centos.yml
  when: ( ansible_distribution == "CentOS" and YUM2PROXY is success)

- name: Copiando arquivos Base Linux
  import_tasks: files.yml
  when: ( ansible_system == "Linux" )

- name: Aplicando PAM Limits
  import_tasks: pamlimits.yml
  when: ( ansible_system == "Linux" )
...