---
# tasks file for iac-ansible-common-server

- name: Instalar pacotes para o "{{ ansible_distribution }}" versão "{{ ansible_distribution_major_version }}"   
  yum: 
    name: "{{ item }}"
    state: latest 
  with_items:
    - bash-completion
    - bash-completion-extras
    - bind-utils
    - bzip2
    - cifs-utils
    - curl
    - epel-release
    - finger
    - htop
    - lsof
    - mlocate
    - nfs-utils
    - nmap
    - screen
    - sudo
    - sysstat
    - tcpdump
    - tree
    - tzdata
    - tuned
    - unzip
    - vim
    - zip
    - wget
  register: PACKAGE    
  when: 
    - ansible_distribution == "CentOS" 
    - YUM2PROXY is success
...
