---
# tasks file for ansible-role-commonserver

- name: Instalar pacotes para o "{{ ansible_distribution }}" versão "{{ ansible_distribution_major_version }}"
  apt: 
    name: "{{ item }}" 
    state: latest 
    update_cache: true
  with_items:
    - bash-completion
    - bzip2
    - chrony
    - curl
    - cifs-utils
    - dnsutils
    - finger
    - htop
    - lsof
    - mlocate
    - nfs-common
    - nmap
    - net-tools
    - screen
    - sudo
    - sysstat
    - tcpdump
    - tree
    - tzdata
    - unzip
    - vim
    - wget
    - zip
  register: DEBIANPACKAGE
  when: 
    - ansible_os_family == "Debian" 
    - APT2PROXY is success
...