---
# tasks file for iac-ansible-common-server

- name: Instalar pacotes para o "{{ ansible_distribution }}" versão "{{ ansible_distribution_major_version }}"
  yum: 
    name: "{{ item }}" 
    state: latest 
  with_items:
    - bash-completion
    - bash-completion-extras
    - bind-utils
    - bzip2
    - cifs-utils
    - curl
    - finger
    - htop
    - lsof
    - mlocate
    - nfs-utils
    - nmap
    - screen
    - sudo
    - sysstat
    - tcpdump
    - tree
    - tzdata
    - unzip
    - vim
    - zip
    - wget
  register: PACKAGE
  when: 
    - ansible_distribution == "RedHat" 
    - YUM2PROXY is success 
    - REDHATREGISTRADO is success
...