---
# tasks file for iac-ansible-common-server

- name: Instalar pacotes base (OS base Debian)
  apt: 
    name: "{{ item }}" 
    state: latest 
    update_cache: true
  with_items:
    - bash-completion
    - bzip2
    - chrony
    - curl
    - cifs-utils
    - dnsutils
    - finger
    - htop
    - lsof
    - mlocate
    - nfs-common
    - nmap
    - net-tools
    - screen
    - sudo
    - sysstat
    - tcpdump
    - tree
    - tzdata
    - unzip
    - vim
    - wget
    - zip
  register: DEBIANPACKAGE
  when: ( ansible_os_family == "Debian" and APT2PROXY is success )
...
