---
- name: Start chronyd
  systemd:
    state: started
    name:  chronyd.service
    enabled: yes
  when: 
    - ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
    - ansible_os_family == "Debian" and ansible_distribution_major_version == "7"
    - ansible_service_mgr == "systemd"
    
# handlers file for common-server
- name: restart rsyslog
  service: 
    name: rsyslog 
    state: restarted
#
# - name: restart sshd
#   service: name=sshd state=restarted
#   when: ansible_os_family == 'RedHat'
#
# - name: restart ssh
#   service: name=ssh state=restarted
#   when: ansible_os_family == 'Debian'
#
# - name: restart snmpd
#   service: name=snmpd state=restarted
#
# - name: restart systemd2ovirt-guest-agent
#     systemd:
#    state: restarted
#    name:  ovirt-guest-agent.service
#
# - name: start snmpd
#   service:
#     name: snmpd
#     state: started
#   when: ( ansible_os_family == 'RedHat'  )
#
- name: enable snmpd at boot
  service:
    name: snmpd
    enabled: yes
#  when: ( ansible_os_family == 'RedHat'  )
#  ansible_os_family == 'RedHat' and ansible_distribution_major_version == "7"

- name: "Start Tuned"
  systemd:
    state: started
    name: tuned.service
    enabled: yes
    force: yes
  ignore_errors: yes
  when: 
    - ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
    - ansible_service_mgr == "systemd"
    
- name: "Disable Firewalld"
  systemd:
    state: stopped
    name: firewalld.service     
    enabled: no
    masked: yes
    force: yes
  ignore_errors: yes
  when: 
    - ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
    - ansible_service_mgr == "systemd"
## SystemD
- name: Start {{ service_name }}
  systemd:
    state: started
    name: {{ service_name }}.service
    enabled: yes
    force: yes
  ignore_errors: yes
  when: 
    - ansible_service_mgr == "systemd"

- name: Stop {{ service_name }}
  systemd:
    state: stopped
    name: {{ service_name }}.service
    enabled: yes
    force: yes
  ignore_errors: yes
  when: 
    - ansible_service_mgr == "systemd"
    
- name: Restart {{ service_name }}
  systemd:
    state: restarted
    name: {{ service_name }}.service
    force: yes
  ignore_errors: yes
  when: 
    - ansible_service_mgr == "systemd"

- name: Reload {{ service_name }}
  systemd:
    state: reloaded
    name: {{ service_name }}.service
    force: yes
  ignore_errors: yes
  when: 
    - ansible_service_mgr == "systemd"     

## SystemV
- name: Start {{ service_name }}
  service:
    state: started
    name: {{ service_name }}
    enabled: yes
  when: 
    - ansible_service_mgr == "service"

- name: Stop {{ service_name }}
  service:
    state: stopped
    name: {{ service_name }}
    enabled: yes
  when: 
    - ansible_service_mgr == "service"
    
- name: Restart {{ service_name }}
  service:
    state: restarted
    name: {{ service_name }}
  when: 
    - ansible_service_mgr == "service"

- name: Reload {{ service_name }}
  service:
    state: reloaded
    name: {{ service_name }}
  when: 
    - ansible_service_mgr == "service"
...
...
