---
- hosts: all
  become: yes
  gather_facts: False

  tasks:

  - shell: |
      for a in /var/adm/* /var/log/*
      do
      [ -f $a ] && sudo chmod 640 $a -v
      [ -d $a ] && chmod 750 $a -v
      done
      exit 0

  - shell: if [ -f "{{ item }}" ] ; then sudo chmod og-w "{{ item }}" -v ; fi
    loop:
      - /etc/dhcp/dhclient-eth0.conf

  - shell: if [ -f "{{ item }}" ] ; then sudo chmod 0700 "{{ item }}" -v ; fi
    loop:
      - /usr/sbin/sendmail
      - /etc/alternatives/mta

   - shell: if [ -f "{{ item }}" ] ; then sudo chmod -s "{{ item }}" -v ; fi
     loop:
       - "{{ lookup('file', 'binarios.txt') }}"
       - /usr/bin/at
       - /usr/bin/screen
       - /usr/bin/wall

   - shell: if [ -f "{{ item }}" ] ; then sudo chmod 750 "{{ item }}" -v && chown -R -v named "{{ item }}" ; fi
     loop:
       - /etc/named*
       - /var/named*
  -
  - shell: if [ -f "{{ item }}" ] ; then sudo chown -v root:ec2-user "{{ item }}" ; fi
    loop:
      - /usr/bin/gcc
      - /usr/bin/cc

  - shell: chkconfig "{{ item }}" off 2>> /dev/null
    loop:
      - NetworkManager-wait-online
      - spice-vdagentd
      - rtkit-daemon
      - initial-setup-text
      - cups
      - accounts-daemon
