---
- hosts: all
  become: yes
  gather_facts: False

  tasks:

  - file:
      path: /etc/mail/empty.txt
      state: touch
      owner: root
      group: root
      mode: 0640
    tags: file
    register: fileok

  - lineinfile:
      path: /etc/mail/sendmail.cf
      regexp: '^{{ item }}'
      state: absent
    loop:
      - "O SmtpGreetingMessage="
      - "O DontBlameSendmail="
      - "O PrivacyOptions="
    register: result

  - lineinfile:
      path: /etc/mail/sendmail.cf
      state: present
      line:
    loop:
      - "O SmtpGreetingMessage="
      - "O DontBlameSendmail=safe"
      - "O HelpFile=/etc/mail/empty.txt"
      - "O PrivacyOptions=authwarnings,novrfy,noexpn,restrictqrun,restrictmailq"
    when: result is success
