---
- hosts: all
  become: yes
  gather_facts: False

  tasks:

  - lineinfile:
      path: /etc/fstab
      regexp: '^{{ item }}'
      state: absent
    loop:
      - tmpfs
    register: result

  - lineinfile:
      path: /etc/fstab
      state: present
      line: "tmpfs\t /dev/shm\t tmpfs\t defaults,nodev,noexec,nosuid\t 0 0"
    when: result is success
